//
//  TableViewMenuItem.swift
//  UIKit-Storyboard
//
//  Created by Kamil Gomółka on 03/02/2022.
//

import Foundation

enum CellStyleMenuItem: String, MenuItemProtocol {
    case defaultFont
    case body
    case title3
    case longText
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var storyboardName: String {
        return "TableView"
    }
    
    var viewControllerIdentifier: String? {
        switch self {
        case .defaultFont:
            return "CellStyleDefaultFontViewController"
        case .body:
            return "CellStyleBodyViewController"
        case .title3:
            return "CellStyleTitle3ViewController"
        case .longText:
            return "CellStyleLongTextViewController"
        }
    }
}
