//
//  ScrollViewMenuItem.swift
//  UIKit-Storyboard
//
//  Created by Kamil Gomółka on 06/12/2021.
//

import Foundation

enum ScrollViewMenuItem: String, MenuItemProtocol {
    case vertical
    case horizontal
    case twoDirections
    case withNoContentLayoutGuides
    case withKeyboard
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var storyboardName: String {
        switch self {
        case .vertical:
            return "ScrollViewVertical"
        case .horizontal:
            return "ScrollViewHorizontal"
        case .twoDirections:
            return "ScrollViewTwoDirections"
        case .withNoContentLayoutGuides:
            return "ScrollViewWithNoContentLayoutGuides"
        case .withKeyboard:
            return "ScrollViewWithKeyboard"
        }
    }
}
