//
//  ButtonMenuItem.swift
//  UIKit-Storyboard
//
//  Created by Kamil Gomółka on 21/01/2022.
//

import Foundation

enum ButtonMenuItem: String, MenuItemProtocol {
    case buttonStyles
    case systemSizes
    case cornerStyle
    case imagePlacement
    case toggleButton
    case other
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var storyboardName: String {
        switch self {
        case .buttonStyles:
            return "ButtonStyles"
        case .systemSizes:
            return "ButtonSystemSizes"
        case .cornerStyle:
            return "ButtonCornerStyle"
        case .imagePlacement:
            return "ButtonImagePlacement"
        case .toggleButton:
            return "ButtonToggle"
        case .other:
            return "OtherButtons"
        }
    }
}
