//
//  TableViewStyleMenuItem.swift
//  UIKit-Storyboard
//
//  Created by Kamil Gomółka on 28/01/2022.
//

import Foundation

enum TableViewStyleMenuItem: String, MenuItemProtocol {
    case plain
    case grouped
    case insetGrouped
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var storyboardName: String {
        return "TableView"
    }
    
    var viewControllerIdentifier: String? {
        switch self {
        case .plain:
            return "TableViewStylePlainViewController"
        case .grouped:
            return "TableViewStyleGroupedViewController"
        case .insetGrouped:
            return "TableViewStyleInsetGroupedViewController"
        }
    }
}
